In [1]:
from pynq import Overlay
ol = Overlay('./acc1.bit')
mm = ol.vmm1_0

/usr/local/lib/python3.6/dist-packages/pynq/overlay.py:299: UserWarning: Users will not get PARAMETERS / REGISTERS information through TCL files. HWH file is recommended.
  warnings.warn(message, UserWarning)


In [2]:
import time

In [4]:
start_time = time.time()
mm.write(0x00,1)
mm.write(0x04,2)
mm.write(0x08,3)
mm.write(0x0C,4)
o1 = mm.read(0x10)
o2 = mm.read(0x14)
o3 = mm.read(0x18)
o4 = mm.read(0x1C)
stop_time = time.time()

In [5]:
sw_exec_time = stop_time - start_time
print('Matrix execution time: ',sw_exec_time)
print(o1)
print(o2)
print(o3)
print(o4) 

Matrix execution time:  0.0036170482635498047
10
10
10
10


In [6]:
import numpy as np

start_time = time.time()
 
x = np.array([3, 4, 5, 6])
w = np.ones((4, 4))
o = x.dot(w)

stop_time = time.time()

sw_exec_time = stop_time - start_time

print(x)
print(w)
print(o)

print('Matrix execution time: ',sw_exec_time)

[3 4 5 6]
[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]
[ 18.  18.  18.  18.]
Matrix execution time:  0.02223682403564453
